### ISSUE TITLE
Create a user registration system for the discord bot

### ISSUE THREAD

**Issue by dusklight00** [namanko/OctoBot#3]
Create a discord registration process where you ask the user for their github profile url and then on the database you store the following parameters
- Github URL
- Total commits set to 0
- Total PR set to 0
- Total Community Chats set to 0

**Comment by namanko** [comment]
Setup a user registration system which inserts a new entry if not present else updates the git_url using command "?reg"

Sample usage:
```
?reg https://github.com/namanko
```

This sends a dm to user saying Info Updated

The database reflects this change
![gitdata](https://github.com/namanko/OctoBot/assets/53829601/568845df-f19c-4ce1-a03f-340b87232db9)

this doesnt update commits PR and community chat and simply sets it to 0 the first time it is used (for registration)
